# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\lbh\Desktop\SoftwareProject\CooperateWork\UI\Huarong.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#这里仅为测试UI用，没什么其他用处
import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(966, 665)
        self.Gamestart = QtWidgets.QPushButton(Dialog)
        self.Gamestart.setGeometry(QtCore.QRect(160, 430, 111, 61))
        self.Gamestart.setObjectName("Gamestart")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(160, 60, 341, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pciture1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pciture1.setText("")
        self.pciture1.setScaledContents(True)
        self.pciture1.setObjectName("pciture1")
        self.gridLayout.addWidget(self.pciture1, 0, 0, 1, 1)
        self.picture2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.picture2.setText("")
        self.picture2.setScaledContents(True)
        self.picture2.setObjectName("picture2")
        self.gridLayout.addWidget(self.picture2, 0, 1, 1, 1)
        self.picture8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.picture8.setText("")
        self.picture8.setScaledContents(True)
        self.picture8.setObjectName("picture8")
        self.gridLayout.addWidget(self.picture8, 2, 1, 1, 1)
        self.picture5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.picture5.setText("")
        self.picture5.setScaledContents(True)
        self.picture5.setObjectName("picture5")
        self.gridLayout.addWidget(self.picture5, 1, 1, 1, 1)
        self.picture4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.picture4.setText("")
        self.picture4.setScaledContents(True)
        self.picture4.setObjectName("picture4")
        self.gridLayout.addWidget(self.picture4, 1, 0, 1, 1)
        self.picture7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.picture7.setText("")
        self.picture7.setScaledContents(True)
        self.picture7.setObjectName("picture7")
        self.gridLayout.addWidget(self.picture7, 2, 0, 1, 1)
        self.picture10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.picture10.setText("")
        self.picture10.setScaledContents(True)
        self.picture10.setObjectName("picture10")
        self.gridLayout.addWidget(self.picture10, 2, 2, 1, 1)
        self.picture6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.picture6.setText("")
        self.picture6.setScaledContents(True)
        self.picture6.setObjectName("picture6")
        self.gridLayout.addWidget(self.picture6, 1, 2, 1, 1)
        self.picture3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.picture3.setText("")
        self.picture3.setScaledContents(True)
        self.picture3.setObjectName("picture3")
        self.gridLayout.addWidget(self.picture3, 0, 2, 1, 1)
        self.tips = QtWidgets.QLabel(Dialog)
        self.tips.setGeometry(QtCore.QRect(610, 90, 130, 130))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tips.sizePolicy().hasHeightForWidth())
        self.tips.setSizePolicy(sizePolicy)
        self.tips.setMaximumSize(QtCore.QSize(400, 400))
        self.tips.setBaseSize(QtCore.QSize(400, 400))
        self.tips.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.tips.setObjectName("tips")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Gamestart.setText(_translate("Dialog", "start"))
        self.tips.setText(_translate("Dialog", "提示："))
if __name__ == "__main__":
  app = QtWidgets.QApplication(sys.argv) # 创建一个QApplication，也就是你要开发的软件app
  MainWindow = QtWidgets.QMainWindow()  # 创建一个QMainWindow，用来装载你需要的各种组件、控件
  ui = Ui_Dialog()            # ui是你创建的ui类的实例化对象
  ui.setupUi(MainWindow)         # 执行类中的setupUi方法，方法的参数是第二步中创建的QMainWindow
  MainWindow.show()            # 执行QMainWindow的show()方法，显示这个QMainWindow
  sys.exit(app.exec_())   